// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:collection/collection.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<U8Array32> deriveKey({
  required SecretString password,
  required List<int> salt,
}) => RustLib.instance.api.crateApiCryptoDeriveKey(
  password: password,
  salt: salt,
);

Future<(Uint8List, U8Array12)> encrypt({
  required List<int> data,
  required U8Array32 key,
}) => RustLib.instance.api.crateApiCryptoEncrypt(data: data, key: key);

Future<Uint8List> decrypt({
  required List<int> ciphertext,
  required U8Array32 key,
  required U8Array12 nonceBytes,
}) => RustLib.instance.api.crateApiCryptoDecrypt(
  ciphertext: ciphertext,
  key: key,
  nonceBytes: nonceBytes,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Secret < String >>>
abstract class SecretString implements RustOpaqueInterface {}

class U8Array12 extends NonGrowableListView<int> {
  static const arraySize = 12;

  @internal
  Uint8List get inner => _inner;
  final Uint8List _inner;

  U8Array12(this._inner) : assert(_inner.length == arraySize), super(_inner);

  U8Array12.init() : this(Uint8List(arraySize));
}

class U8Array32 extends NonGrowableListView<int> {
  static const arraySize = 32;

  @internal
  Uint8List get inner => _inner;
  final Uint8List _inner;

  U8Array32(this._inner) : assert(_inner.length == arraySize), super(_inner);

  U8Array32.init() : this(Uint8List(arraySize));
}
