// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `zeroize`, `zeroize`

class Attachment {
  final String name;
  final Uint8List data;

  const Attachment({required this.name, required this.data});

  @override
  int get hashCode => name.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Attachment &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          data == other.data;
}

class Vault {
  final List<VaultItem> items;
  final int version;

  const Vault({required this.items, required this.version});

  static Future<Vault> default_() =>
      RustLib.instance.api.crateApiModelVaultDefault();

  @override
  int get hashCode => items.hashCode ^ version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Vault &&
          runtimeType == other.runtimeType &&
          items == other.items &&
          version == other.version;
}

class VaultItem {
  final String id;
  final String title;
  final String? username;
  final String? password;
  final String? url;
  final String? notes;
  final String? category;
  final List<Attachment> attachments;
  final PlatformInt64 updatedAt;

  const VaultItem({
    required this.id,
    required this.title,
    this.username,
    this.password,
    this.url,
    this.notes,
    this.category,
    required this.attachments,
    required this.updatedAt,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<VaultItem> newInstance({required String title}) =>
      RustLib.instance.api.crateApiModelVaultItemNew(title: title);

  @override
  int get hashCode =>
      id.hashCode ^
      title.hashCode ^
      username.hashCode ^
      password.hashCode ^
      url.hashCode ^
      notes.hashCode ^
      category.hashCode ^
      attachments.hashCode ^
      updatedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VaultItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          title == other.title &&
          username == other.username &&
          password == other.password &&
          url == other.url &&
          notes == other.notes &&
          category == other.category &&
          attachments == other.attachments &&
          updatedAt == other.updatedAt;
}
