// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'model.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EncryptedVault`

Future<void> saveVault({
  required String path,
  required String masterPassword,
  required Vault vault,
}) => RustLib.instance.api.crateApiVaultSaveVault(
  path: path,
  masterPassword: masterPassword,
  vault: vault,
);

Future<Vault> loadVault({
  required String path,
  required String masterPassword,
}) => RustLib.instance.api.crateApiVaultLoadVault(
  path: path,
  masterPassword: masterPassword,
);

Future<Vault> createEmptyVault() =>
    RustLib.instance.api.crateApiVaultCreateEmptyVault();

Future<Vault> addItem({required Vault vault, required String title}) =>
    RustLib.instance.api.crateApiVaultAddItem(vault: vault, title: title);

Future<Vault> updateItem({
  required Vault vault,
  required VaultItem updatedItem,
}) => RustLib.instance.api.crateApiVaultUpdateItem(
  vault: vault,
  updatedItem: updatedItem,
);

Future<Vault> deleteItem({required Vault vault, required String id}) =>
    RustLib.instance.api.crateApiVaultDeleteItem(vault: vault, id: id);
